In [ ]:
#Numpy est une extension du language de programmation Python, 
#destinée à manipuler des matrices ou tableaux multidimensionnels ainsi que des fonctions 
#mathématiques opérant sur ces tableaux
import numpy as np

# Creation de vecteurs et des matrices

In [119]:
#Creation d'une matrice :
b = np.array([i for i in range(6)])
b

array([0, 1, 2, 3, 4, 5])

In [120]:
a = np.arange(1, 41, 2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [121]:
#Redimensionnement :
a = a.reshape(4,5)
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [122]:
b = b.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [123]:
#Conversion :
c = b.astype(np.float)

In [124]:
#Typage des données : 
print(f"La matrice de a est de type : {a.dtype}")
print(f"La matrice de b est de type : {b.dtype}")
print(f"La matrice de c est de type : {c.dtype}")

La matrice de a est de type : int32
La matrice de b est de type : int32
La matrice de c est de type : float64


In [125]:
#creation d'une matrice sans reshape:
d = np.ones((3,4),"int32")
print(f"La matrice d est : {d.dtype}\n{d}")

La matrice d est : int32
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


# Extraction des valeurs

In [126]:
#Plage d'indices:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [127]:
b[1,2]

5

In [128]:
b[0]

array([0, 1, 2])

In [129]:
b[0, 1:3]

array([1, 2])

Ecriture générique:

b[<font color='red'>début:fin</font>, <font color='green'>début:fin</font>] 

#red : selection de la ligne 
#green : selection de l'élément(s) dans la ligne

In [130]:
#Indiçage booléen:
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [131]:
a<22

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False]])

In [132]:
a[a<22]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [133]:
#Tri et recherche:
np.max(a, axis=0) # axis = 0 -> recherche sur colonne

array([31, 33, 35, 37, 39])

In [134]:
np.min(a, axis=1) # axis = 1 -> recherche sur ligne

array([ 1, 11, 21, 31])

# Calcul sur les vecteurs et les matrices:

In [135]:
#Calcul statistiques : 
b

array([[0, 1, 2],
       [3, 4, 5]])

In [136]:
#moyenne:
np.mean(b)

2.5

In [137]:
#moyenne ligne ou colonne:
print(f"Moyenne de toutes les colonnes : {np.mean(b, axis = 0)}") 
print(f"Moyenne de toutes les lignes : {np.mean(b, axis = 1)}") 

Moyenne de toutes les colonnes : [1.5 2.5 3.5]
Moyenne de toutes les lignes : [1. 4.]


In [138]:
#médiane:
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [139]:
np.median(a, axis=0)

array([16., 18., 20., 22., 24.])

In [140]:
np.median(a, axis = 1)

array([ 5., 15., 25., 35.])

In [3]:
#variance:
import numpy as np
a = np.arange(1, 41, 2)
a = a.reshape(4,5)
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [4]:
np.var(a, axis=0)

array([125., 125., 125., 125., 125.])

In [5]:
np.var(a, axis=1)

array([8., 8., 8., 8.])

In [16]:
#quantile
print("Q2 quantile of arr : ", np.quantile(a, .50)) 
print("Q1 quantile of arr : ", np.quantile(a, .25)) 
print("Q3 quantile of arr : ", np.quantile(a, .75)) 

Q2 quantile of arr :  20.0
Q1 quantile of arr :  10.5
Q3 quantile of arr :  29.5


In [18]:
#somme
np.sum(a, axis=0)

array([64, 72, 80, 88, 96])

In [19]:
np.sum(a, axis=1)

array([ 25,  75, 125, 175])

In [21]:
#somme cumulé
np.cumsum(a)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400], dtype=int32)

In [23]:
#Multiplication entre matrices
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [24]:
#Multiplication entre vecteurs
np.multiply(a,b)

array([[ 5, 12],
       [21, 32]])

#### Lien utile pour la manipulation de Numpy:
http://eric.univ-lyon2.fr/~ricco/cours/slides/PH%20-%20matrices%20avec%20numpy.pdf